### ISSUE TITLE
Atualizar Laravel para a versão 5.7

### ISSUE THREAD

**Issue by macecchi** [caronae/caronae-backend#19]
Atualmente estamos usando a versão 5.5 do Laravel. No entanto, o Laravel já tem a versão 5.7 disponível.

Pra atualizar, precisamos seguir os passos do Upgrade Guide abaixo:
* Atualizando da 5.5 pra 5.6: https://laravel.com/docs/5.6/upgrade#upgrade-5.6.0
* Atualizando da 5.6 pra 5.7: https://laravel.com/docs/5.7/upgrade

**Comment by itepifanio** [comment]
Trabalhando nisso

**Comment by macecchi** [comment]
Valeu @itepifanio! Se precisar de algum suporte só avisar aqui que posso ajudar!

**Comment by itepifanio** [comment]
@macecchi aparentemente a dependencia "laracasts/generators" não tem versão disponível para o laravel 5.6 sempre aparece o erro ` The "http://packagist.org/p/laracasts/generators%24ad9b9c472010df3d53db977b  
  830a278b89d6183e9580a43eb8ff610707e922ce.json" file could not be downloaded  
  : failed to open stream: Connection timed out ` (e não, não é erro de conexão). Abri uma issue no repositório deles para esclarecer isso, visto que não achei muita coisa na internet sobre.

**Comment by macecchi** [comment]
@itepifanio Eu acho que essa lib nem é necessária tá no `require-dev` pra falar a verdade. Se remover ela, dá certo? Ou tem alguma coisa que depende dela ainda?
Eu acho que adicionei ela por causa do https://github.com/Laravel-Backpack/CRUD/, mas a gente nem usa recurso de generators dessa lib, pra falar a verdade.

**Comment by itepifanio** [comment]
Aparentemente era isso sim. Como vocês não utilizam esse pacote eu tomei a liberdade de remove-lo por enquanto, tudo bem? Amanhã subo o Pull request.
