### ISSUE TITLE
Melhorar a pesquisa por nome do usuário na área administrativa

### ISSUE THREAD

**Issue by macecchi** [caronae/caronae-backend#33]
Atualmente a **pesquisa por usuários** pelo nome na área administrativa - http://localhost:8000/admin/users - funciona fazendo um `ILIKE` ([case-insensitive LIKE](https://www.postgresql.org/docs/9.6/static/functions-matching.html)) no banco de dados. No entanto, isso não funciona bem quando queremos pesquisar por uma **composição** do nome da pessoa - por exemplo, pesquisando pelo primeiro e último nome, como _Bruno Neto_, não encontraria um usuário _Bruno Mateus Quintana Neto_, pois o último termo não aparece junto com o primeiro.

![2018-10-20 21 11 15](https://user-images.githubusercontent.com/5282467/47261759-2b8ea700-d4ad-11e8-8901-e43cf907336d.gif)

Isso é um problema porque às vezes os usuários mandam mensagens de suporte só usando o primeiro e último nome, e aí essa busca pela equipe acaba sendo manual :(

No controller, essa query é montada aqui - https://github.com/caronae/caronae-backend/blob/master/app/Http/Controllers/Admin/UserController.php#L39-L41. Esse controller usa a biblioteca [Laravel Backpack CRUD](https://github.com/Laravel-Backpack/CRUD), mas isso não deve importar muito, porque essa query já está sendo personalizada por nós.

Uma possível solução seria substituir os espaços da pesquisa por um `%`, mas não testei e não sei se existe uma solução melhor.

**Bônus**: conseguir pesquisar ignorando acentos - por exemplo, a pesquisa por 'antonio' encontraria um usuário chamado 'Antônio'. Isso atualmente não funciona. Não sei sei o banco de dados (PostgreSQL 9.6) já possui alguma função pra considerar isso na pesquisa.

**Comment by jcavalin** [comment]
Para resolver os acentos, eu encontrei [esta solução](https://stackoverflow.com/a/11007216), porém não sei como eu mandaria a ativação dessa extensão na PR. 
Se você puder me indicar a melhor maneira de fazer isso eu posso realizar outra PR com essa solução.

**Comment by macecchi** [comment]
@jcavalin Obrigado! Não entendi direito se é só uma query que precisa rodar pra ativar essa extensão. Se for só isso, vc pode criar uma migration parecida com essa: 
https://github.com/caronae/caronae-backend/blob/master/database/migrations/2017_04_21_185740_create_integer_like_operator.php

**Comment by macecchi** [comment]
@jcavalin 
Pelo que testei aqui local é só isso mesmo! É só criar uma migração com 
```sql
CREATE EXTENSION IF NOT EXISTS unaccent;
```
e pra reverter
```sql
DROP EXTENSION IF EXISTS unaccent;
```

e aí consultar com 
```sql
WHERE  unaccent(name) ILIKE '%'||unaccent('antonio')||'%';
```

O que acha? Quer fazer esse PR também? :D 
Qualquer coisa eu posso fazer mesmo :)

**Comment by jcavalin** [comment]
@macecchi 
Vou refatorar o código desse PR e já adiciono isso junto. 
Obrigado pelo esclarecimento.

**Comment by macecchi** [comment]
Implementado pelo #35 e #37. Valeu, @jcavalin! 🎉
