### ISSUE TITLE
Foto da usuária não aparece na área administrativa

### ISSUE THREAD

**Issue by macecchi** [caronae/caronae-backend#40]
Na visualização da usuária na área administrativa, a imagem do usuário está quebrada, e o Laravel está inserindo um valor `1` ao invés da URL da imagem do usuário.

Exemplo: http://localhost:8000/admin/users/1
![screen shot 2018-10-28 at 11 42 37](https://user-images.githubusercontent.com/5282467/47617550-0dc1d300-daa7-11e8-9ee6-153aff35905b.png)

Essa view é montada aqui - https://github.com/caronae/caronae-backend/blob/master/resources/views/users/user.blade.php#L3 - com uma imagem padrão caso não exista, mas por algum motivo essa lógica não funciona mais.

Um chute é que algum update do Laravel quebrou essa sintaxe (ou ela sempre esteve errada).

**Comment by arthur322** [comment]
Posso dar uma olhada?

**Comment by macecchi** [comment]
Corrigido pelo #44.
