### ISSUE TITLE
Atualizar Laravel para a versão 5.8

### ISSUE THREAD

**Issue by macecchi** [caronae/caronae-backend#46]
Atualmente estamos na versão 5.7 do Laravel, mas podemos atualizar pra versão 5.8 seguindo o [guia de upgrade](https://laravel.com/docs/5.8/upgrade).

Dando uma breve olhada, o ponto de maior atenção no upgrade seria o _Cache TTL In Seconds_ nas classes onde usamos cache.

Também seria bom ver os diffs dessa versão no próprio GitHub pra manter arquivos de configuração e outras coisas nos padrões mais recentes.

**Comment by wanderleyfa** [comment]
Posso fazer isso, como procedo?

**Comment by macecchi** [comment]
Oi @wanderleyfa! 
Eu costumo seguir esse guia oficial - https://laravel.com/docs/5.8/upgrade#upgrade-5.8.0 - com as mudanças mais importantes, vendo se no nosso código tem algo que se aplica (tipo o caso do Cache que eu sinalizei na issue). E aí [rodar os testes](https://github.com/caronae/caronae-backend#testes) pra ver se tudo continua funcionando :)

Outra coisa que é legal fazer é usar a comparação entre versões do GitHub - https://github.com/laravel/laravel/compare/5.7...master - pra ver se mudou algo a mais nos arquivos de configuração, só pra deixar os arquivos nossos atualizados tb.

Daí é só mandar o PR e se precisar de mais algum ajuste eu te falo ou eu mesmo corrijo.
E fica a vontade pra falar aqui se precisar de apoio com alguma coisa. Também tô no Telegram (@mariocecchi) se preferir algo mais direto :)

**Comment by wanderleyfa** [comment]
ok, vou analisar aqui, e fazer isso, te deixo ciente do que estou fazendo.

**Comment by me42th** [comment]
A issue ainda está aberta?

**Comment by macecchi** [comment]
Oi @me42th! O projeto foi descontinuado então não é mais uma necessidade. Vou atualizar os repositórios do projeto para apenas leitura pra evitar confusão ;)
