### ISSUE TITLE
Localisation?

### ISSUE THREAD

**Issue by GerfriedC** [caronae/caronae-backend#50]
Are there plans to introduce other languages?
many thanks

**Comment by macecchi** [comment]
Sorry, unfortunately we don’t have any plans on working with internationalisation. Laravel offers some resources on this so it shouldn’t be a huge effort, at least considering the backend.

The project is in a kind of hiatus right now, but feel free to contribute if you’d like :)

I’ll be closing this issue to avoid confusion but we’re open to pull requests 😉
