### ISSUE TITLE
Listar apenas caronas da instituição do usuário

### ISSUE THREAD

**Issue by macecchi** [caronae/caronae-backend#6]
**O usuário do Caronaê deve poder visualizar apenas as caronas oferecidas _na sua própria instituição_**. 

Exemplo: se sou aluno da UFRJ, não posso visualizar caronas ofertadas por alunos da UNIRIO.

Para isso, a listagem de caronas que vem da API deve levar em consideração a instituição do usuário que fez a requisição e retornar apenas as caronas da instituição a que pertence.

## Detalhes

Cada usuário já é associado a uma instituição e cada carona também. É necessário adaptar a rota de listar/pesquisar caronas (`RideController::index`) para filtrar apenas as caronas que pertencem a motoristas da mesma instituição do usuário atual.

## Extras

A rota de `requestJoin` (por onde pode solicitar participar numa carona) também deve impedir que um usuário de uma instituição solicite participar de uma carona de outra instituição.

**Comment by macecchi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Listar caronas apenas da instituição do usuário](https://trello.com/c/uEWYLhAn/282-listar-caronas-apenas-da-institui%C3%A7%C3%A3o-do-usu%C3%A1rio)

**Comment by danielsouzaaf** [comment]
oi @macecchi, tô dando uma olhadinha nessa issue!

**Comment by macecchi** [comment]
@danielsouzaaf e aí, tá conseguindo se entender com o código? me fala aí se precisar de alguma coisa! ah, e caso acho que não vá conseguir fazer, nos avisa que passamos pra outra pessoa :)

**Comment by danielsouzaaf** [comment]
fala @macecchi, acabou que quando fui setar o ambiente de dev deu um erro nos seeders, fiquei de ver um workaround para poder testar e me familiarizar com o sistema mas não deu em nada. :/
se quiser deixar para outra pessoa, fica a seu critério, mas acho que vou dar mais uma olhadinha sim

**Comment by macecchi** [comment]
@danielsouzaaf putz :/ 
Pior que os seeders tão quebrados mesmo. Eu até criei o #7 pra listar isso. Vou ver aqui se consigo pegar o #7 então pra resolver isso e aí te desbloqueio. Te aviso quando tiver um progresso!

**Comment by macecchi** [comment]
Implementado no PR #27. Valeu @rpaggi !
