### ISSUE TITLE
Corrigir seeders para popular banco de dados

### ISSUE THREAD

**Issue by macecchi** [caronae/caronae-backend#7]
**O projeto conta com alguns *seeders*, que geram dados aleatórios no banco de dados, que estão desatualizados e, portanto, não funcionam. 😢**

## O que são seeders?

Os seeders permitem que qualquer pessoa desenvolvedora possa criar um banco de dados com algumas caronas e usuários de exemplo para poder testar as coisas e observar como funciona o sistema, sem precisar criar dados iniciais ou depender de um dump com dados reais de usuários.

Por exemplo, se acabei de baixar o projeto e criar o banco de dados, posso executar o comando abaixo e em seguida já teria dados de exemplo para visualizar como o sistema funciona:

```
php artisan db:seed
```

## Detalhes

Os arquivos ficam na pasta https://github.com/caronae/caronae-backend/tree/master/database/seeds.

Os seeds utilizam *factories*, que são funções que criam caronas, usuários etc usando dados aleatórios. No entanto, devido a refatorações e mudanças nos Models, alguns desses seeders (ex: `NeighborhoodSeeder`) precisam ser reescritos usando os novos formatos e outros precisam ser criados (ex: `InstitutionSeeder`).

**Comment by guilhermeportela** [comment]
Olá, @macecchi. Posso trabalhar nessa issue?

**Comment by macecchi** [comment]
Corrigido em #15.
