### ISSUE TITLE
Atualizar Laravel para versão 5.5

### ISSUE THREAD

**Issue by macecchi** [caronae/caronae-backend#8]
Atualmente utilizamos o framework Laravel na versão 5.4. A versão 5.5, que foi lançada este ano, traz diversas melhorias e correções.

O próprio site oficial do Laravel possui um guia de atualização, e estima que o trabalho é de aproximadamente 1 hora.

https://laravel.com/docs/5.5/upgrade

**Comment by macecchi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Atualizar Laravel para 5.5](https://trello.com/c/IpgTLvXf/263-atualizar-laravel-para-55)

**Comment by tonysm** [comment]
Vou tentar fazer essa issue hoje a noite, tudo bem? :)

**Comment by macecchi** [comment]
Massa, @tonysm! Comenta aqui caso tiver qualquer dúvida e posso te ajudar! 😄

**Comment by macecchi** [comment]
@tonysm Mergeado e em produção! 🎉 

Muito obrigado, cara! :)

**Comment by tonysm** [comment]
@macecchi pow, que massa! :D
